# Generated by Django 3.0.3 on 2020-04-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardproductname',
            name='language',
            field=models.CharField(choices=[('english', 'english'), ('hindi', 'hindi'), ('kannada', 'kannada'), ('telugu', 'telugu'), ('tamil', 'tamil'), ('bengali', 'bengali')], max_length=30),
        ),
    ]
