# Generated by Django 3.0.3 on 2020-04-25 14:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20200425_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='marketplace.StandardProduct', verbose_name='Product name'),
            preserve_default=False,
        ),
    ]
